### ISSUE TITLE
[API] R&D: Tagging with Google Vision

### ISSUE THREAD

**Issue by 1000miles** [IchiBizz/IchiBizz#14]
# TODO

Research & Development (R&D)

- [x] Study Google Vision Api
- [ ] Test Images upload via Google Vision

## Nice to have
- [ ] Generate product tags based on uploaded images
