### ISSUE TITLE
[API] Implement GooleMaps on Product Detail Page

### ISSUE THREAD

**Issue by 1000miles** [IchiBizz/IchiBizz#22]
API: https://developers.google.com/maps/documentation/javascript/adding-a-google-map

## TODO

- [x] Study GoolgMaps Api
- [x] Register API key
- [ ] Set 'owner' with session user
- [ ] Set 'wishlist' with session user (nice to have)

```javascript
  <body>
    <div id="map"></div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 8
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
    async defer></script>
  </body>
```
- [x] Implement Marker for GoogleMaps

---

This is a subtask of Github Issue: CRUD on Product Detail page #11

**Comment by ninetteadhikari** [comment]
Decided to switch to MapBox after talking to the TAs
