### ISSUE TITLE
[ROOT] Setup Home Page

### ISSUE THREAD

**Issue by 1000miles** [IchiBizz/IchiBizz#33]
As a visitor if I go to a website (www.example.com) I want to see:

/App.js

- [ ] Logo
- [ ] Slogan (nice to have)
- [ ] Quality images
- [ ] Short description what IchiBizz is about
- [ ]  Signup/Login Option
- [ ]  Navigation:
   - [ ] About (Team)
   - [ ] Products Listing
   - [ ] Contact
   - [ ] Imprint

### TODO:

- [ ] Make sure all data are in place BEFORE login/signup
- [ ] Style the home page (Material UI)
