### ISSUE TITLE
[Concept] Change: Only allow used products for selling

### ISSUE THREAD

**Issue by 1000miles** [IchiBizz/IchiBizz#58]
# Background

If we provide the possibility to also sell new business inventory our marketplace won't be unique anymore and would end up as a market like others. 

We want to prevent that retailers are going to flood the market place with their new products which in the end could lead to new business owners getting desinterested and leaving.

# Suggestion

By default all products must be `used` business inventory but we could improve this by adding other condition types such as

- almost new
- very good
- normal
- partially defect
- defect

## TODO

- [ ] Remove `new` from `condition` in Product schema
- [ ] Remove `new` from the form for `CREATE` and `EDIT` product
- [ ] Introduce new condition types 
  - [ ] to Product model
  - [ ] CREATE/EDIT form
