### ISSUE TITLE
[EPIC] Fix Product pages

### ISSUE THREAD

**Issue by 1000miles** [IchiBizz/IchiBizz#59]
# Bugs

### New

- [ ] Image upload on new product page leads to broken images when redirected to product details page

### Edit

- [ ] Button from Product Detail Page links to a broken link for EDIT product page
- [ ] TBA

### Show/Edit Product page

- [ ] Google Maps does not show up anymore
